azu/promises-book

- index.adoc
> 韓国語、中国語へのリンクを追加

- _tools/deploy-gh-pages.sh
- index.adoc
PDFがgitignoreで無視されてるため、gh-pagesに入ってない
> PDFがリンク切れを起こしてる

- Ch2_HowToWrite/onrejected-or-catch.adoc
> Fix inline code

- Ch2_HowToWrite/promise-and-array.adoc
- Ch4_AdvancedPromises/resolve-thenable.adoc
- Ch4_AdvancedPromises/src/grouping-promises.js
- Ch4_AdvancedPromises/src/race-delay-timeout/delay-race-cancel-play.js
* `console.log` や `console.error` は値を返さない
* `return console.log(...);` のようになっていた
> 値を返さないメソッドをreturnに設定していたので修正。

- Ch4_AdvancedPromises/src/deferred/deferred.js
> 不要なcallを削除。

- Appendix-Glossary/resource-link.adoc
> 日本語訳へのリンクを追加

- Appendix-Glossary/glossary.adoc
- Appendix-Glossary/resource-link.adoc
- Appendix-Note/beginning-story.adoc
- Ch0_Introduction/readme.adoc
- Ch1_WhatsPromises/promise-overview.adoc
- Ch2_HowToWrite/promise-catch.adoc
- Ch4_AdvancedPromises/race-delay-timeout.adoc
> refactor: es6-status

- Ch4_AdvancedPromises/src/notifications/notification-callback.js
- Ch4_AdvancedPromises/test/notification-thenable-test.js
> Notification APIのサンプルコードを修正

- CONTRIBUTING.md
- Ch4_AdvancedPromises/promise-library.adoc
- gulpfile.js
- package.json
- public/js/console-editor.js
- test/test-helper.js
> ypromiseを外す

- Ch2_HowToWrite/promise-then.adoc
> chore(promise-then): 引数の修正 vaue → value

- public/css/default.css
`text-rendering: optimizeLegibility` is very slow on Google Chrome.
- http://flat.press/develop/2016/02/chrome-freezes/
- https://bocoup.com/weblog/text-rendering
> fix(css): remove "text-rendering: optimizeLegibility" which is bad style

- CONTRIBUTING.md
> docs(CONTRIBUTING): fix commit message convention

- Ch2_HowToWrite/promise-and-array.adoc
- Ch2_HowToWrite/promise-resolve.adoc
- package.json
- jQueryがロードされているページで動くコードに変更
- CORSとXHRについての注意を追加
close #273
> fix: XHRで取得できるリソースとCORSについてを追記

- Ch1_WhatsPromises/what-is-promise.adoc
E言語についてのリンク先が消失していたためWeb Archiveを利用
> fix(ch1): E言語のリンク切れ対応

- .gitignore
- .travis.yml
- Gemfile
- Gemfile.lock
- Makefile
- _tools/build.sh
- _tools/deploy-gh-pages.sh
- readme.md
- lock gem
- always check building pdf
> refactor(deploy): safe deploy

- Appendix-Reference/readme.adoc
- CONTRIBUTING.md
- Ch2_HowToWrite/promise-and-array.adoc
- Ch2_HowToWrite/promise-finally.adoc
- Ch2_HowToWrite/readme.adoc
- Ch4_AdvancedPromises/promise-done.adoc
- gulpfile.js
- package.json
- public/js/console-editor.js
- test/test-helper.js
- yarn.lock
Promise#finallyをCh2とAppendxに追加する。
- core-jsを使う( native-promise-only は Promise#finally をサポートしていない)
fix #284 
fix #296
> feat(ch2): Promise#finally

- Ch4_AdvancedPromises/promise-done.adoc
> refactor(promise-done): Unhandled Rejectionと仕様を追記

- Ch0_Introduction/readme.adoc
> feat(Ch0): jsprimerへの言及を追加

- .travis.yml
- Appendix-Note/beginning-story.adoc
- Appendix-Note/tooling-ci.adoc
- Ch0_Introduction/readme.adoc
- Ch2_HowToWrite/promise-and-array.adoc
- Ch2_HowToWrite/src/multiple-xhr-callback-counter.js
- Ch2_HowToWrite/src/multiple-xhr-callback.js
- Ch2_HowToWrite/src/multiple-xhr-fn.js
- Ch2_HowToWrite/src/multiple-xhr.js
- Ch2_HowToWrite/src/promise-all-xhr.js
- Ch4_AdvancedPromises/promise-library.adoc
- Ch4_AdvancedPromises/promise-sequence.adoc
- Ch4_AdvancedPromises/resolve-thenable.adoc
- Ch4_AdvancedPromises/src/sequence/promise-foreach-xhr.js
- Ch4_AdvancedPromises/src/sequence/promise-reduce-xhr.js
- Ch4_AdvancedPromises/src/sequence/promise-sequence-xhr.js
- Ch5_AsyncFunction/async-function.adoc
- _tools/cli-inject-meta.js
- _tools/cli-rel-to-abs.js
- docinfo.html
- index.adoc
- readme.md
> fix(website): use https

- Ch0_Introduction/readme.adoc
- Ch1_WhatsPromises/what-is-promise.adoc
Arrow Functionの説明とjsprimerへのリンクを追加
fix #324
> refactor(Ch1): Arrow Functionの説明を追加

- Ch1_WhatsPromises/src/xhr-promise.js
- Ch2_HowToWrite/promise-all.adoc
- Ch2_HowToWrite/promise-and-array.adoc
- Ch2_HowToWrite/promise-finally.adoc
- Ch2_HowToWrite/src/multiple-xhr-callback-counter.js
- Ch2_HowToWrite/src/multiple-xhr-callback.js
- Ch2_HowToWrite/src/multiple-xhr.js
- Ch2_HowToWrite/src/promise-all-xhr.js
- Ch4_AdvancedPromises/deferred-promise.adoc
- Ch4_AdvancedPromises/lib/cancelableXHR.js
- Ch4_AdvancedPromises/promise-done.adoc
- Ch4_AdvancedPromises/promise-sequence.adoc
- Ch4_AdvancedPromises/race-delay-timeout.adoc
- Ch4_AdvancedPromises/resolve-thenable.adoc
- Ch4_AdvancedPromises/src/deferred/deferred.js
- Ch4_AdvancedPromises/src/deferred/xhr-deferred.js
- Ch4_AdvancedPromises/src/grouping-promises.js
- Ch4_AdvancedPromises/src/race-delay-timeout/delay-race-cancel.js
- Ch4_AdvancedPromises/src/sequence/promise-foreach-xhr.js
- Ch4_AdvancedPromises/src/sequence/promise-reduce-xhr.js
- Ch4_AdvancedPromises/src/sequence/promise-sequence-xhr.js
- test/inline-script/run-inline-script-test.js
> refactor: use Arrow Function

- Ch4_AdvancedPromises/lib/cancelableXHR.js
- Ch5_AsyncFunction/async-function.adoc
> feat(Ch5): Fetch APIの解説を補足

- Ch4_AdvancedPromises/race-delay-timeout.adoc
> feat(Ch4): FetchとAbortControllerを追加

- Ch4_AdvancedPromises/promise-chain.adoc
- Ch4_AdvancedPromises/test/array-promise-chain-test.js
> feat(Ch4): util.promisifyと.promisesについてを追加

- Ch5_AsyncFunction/async-function-syntax.adoc
I just found the following broken layout when I read your book.
BTW thank you for providing nice book! 👍
> add missing `

- Ch2_HowToWrite/promise-catch.adoc
- Ch5_AsyncFunction/async-function-await.adoc
- Ch5_AsyncFunction/async-function-syntax.adoc
実行することを意図していなさそうなサンプルコードの実行ボタンを非表示にしてみました。
> chore: 実行を意図していなさそうなサンプルコードの実行ボタンを表示しない

- Ch5_AsyncFunction/promise-chain-to-async-function.adoc
とても分かりやすいドキュメントありがとうございます！
誤字と思われる箇所を修正してみました。
ご確認お願いいたします。 🙏
> chore: fix typo

- Ch4_AdvancedPromises/src/race-delay-timeout/delay-race-cancel-play.js
- yarn.lock
> fix(ch4): remove duplicated

- .github/workflows/deploy.yml
- .github/workflows/test.yml
ref https://github.com/actions/runner-images/issues/6002
---
*This change was executed automatically with [Shepherd](https://github.com/NerdWalletOSS/shepherd).* 💚🤖
> CI: update ubuntu-18.04 to ubuntu-latest

- index.adoc
> fix(website): update ribbon

- CONTRIBUTING.md
- readme.md
- README に書いてある 韓国語の ebook のリンクが切れてしまっているようなので修正
-  CONTRIBUTING の誤字脱字修正
> chore: リンク切れ & 誤字脱字修正

- Ch2_HowToWrite/test/then-return-new-promise-test.js
- Ch2_HowToWrite/test/timer-promisefy-test.js
- Ch4_AdvancedPromises/experiment/door-chain.js
- Ch4_AdvancedPromises/race-delay-timeout.adoc
- _tools/README.md
> chore: タイポ修正

- package.json
- yarn.lock
> chore: 使用していない nock を削除
