.travis.yml
Makefile
_tools/deploy-gh-pages.sh
gulpfile.js
package.json
readme.md

```
npm i -g gulp
```
は不要にできるはずなので、ビルドスクリプトを変更する。

node_modulesのgulpのみを使う

---

Ch3_Testing/mocha-promise.adoc
_tools/deploy-gh-pages.sh

```js
assert.deepEqual(error.message === "woo");
```
を
```js
assert(error.message === "woo")
```
へ変更する

Ch3: assert.deepEqualの使い方が間違っている

---

Ch2_HowToWrite/src/promise-then-taska-throw.js

Ch2でのサンプルソース（promise-then-taska-throw.js）にて
セミコロンが抜けていました。
jsbinでソースをコピペするとエラーとなるため、修正のため
pull requestを出した次第です。

fix(src): Ch2でのサンプルソースにセミコロンが抜けていた問題の修正

---

readme.md

README で「を」が抜けていたのを修正

---

Ch2_HowToWrite/promise-all.adoc

`が呼び出すこと事が出来ます` となっていたのを修正しました。

chore(promise-all): Promise.all の概説の不自然な文章を修正

---

Ch1_WhatsPromises/promise-overview.adoc

ES6 Promiseの状態の名前を変更

---

Ch2_HowToWrite/promise-all.adoc

「また」 -> 「または」の修正です。
この pull request とは直接関係ないのですが、[CONTRIBUTING.md の Gitのコミットメッセージ](https://github.com/azu/promises-book/blob/c2b8df3a0550ddba9e15cbc5893bcc02ea20f330/CONTRIBUTING.md#git%E3%81%AE%E3%82%B3%E3%83%9F%E3%83%83%E3%83%88%E3%83%A1%E3%83%83%E3%82%BB%E3%83%BC%E3%82%B8)のリンク先の CONVENTIONS.md がなくなっているようです。

chore(promise-all): fix typo

---

Ch2_HowToWrite/promise-resolve.adoc

jQuery 3.0からDeferredがPromises/A+準拠になるので一言触れておくとよいかと思い、その記述を追加しました。
https://blog.jquery.com/2016/01/14/jquery-3-0-beta-released/

Deferred object will be Promises/A+ compatible on jQuery 3.0 or later.

---

Ch2_HowToWrite/promise-resolve.adoc

jQuery 3では Promise/A+準拠の実装へ変更されたため、
Note紹介した問題は解消されているという点についてを追記
close #241

feat(promise-resolve): jQuery 3についてを追加

---

Ch4_AdvancedPromises/resolve-thenable.adoc

fix(ch4): Notification APIは最新の仕様ではPromiseに対応していることを注記

---

Ch4_AdvancedPromises/promise-done.adoc
Ch4_AdvancedPromises/promise-library.adoc

- core-jsを追加
- Native Promise Only (NPO)を削除
- Promise#finallyをサポートしていないため
- ypromise を削除
　- deprecatedになっているため
- https://github.com/taylorhakes/promise-polyfill を追加
- npmダウンロード数が多い
fix #297

fix(promise-library): polyfillライブラリの変更

---

Ch4_AdvancedPromises/promise-done.adoc

「unhandled rejection**の**検知して→unhandled rejection**を**検知して」の一文字だけの修正です。

chore(promise-done): fix typo

---

Ch5_AsyncFunction/async-function.adoc

`fetchBookTitle()`の`fetch("/json/book.json")`で404エラーになっていました。
現状ココ参照してます。
http://azu.github.io/json/book.json
先頭のスラッシュを削除することでエラーは解消されました。
2.8.1の`getComment()`や`getPeople()`は絶対URLになっています。
揃えようかと思いましたが、変更を少ないよう今回の修正にしました。

fix: /json/book.jsonでfetchエラーになるので絶対パスに変更

---

Ch4_AdvancedPromises/deferred-promise.adoc
Ch4_AdvancedPromises/src/deferred/deferred.js

feat(Ch4): Deferredのクラス化、クラス構文の補足を追加

---

Ch1_WhatsPromises/writing-promises.adoc

ES2015への移行でArrow Functionに過剰修正された関数を名前付き関数式に復元

chore(Ch1): 名前付き関数式の復元

---

Ch1_WhatsPromises/what-is-promise.adoc

https://github.com/azu/promises-book/pull/277 でリンク先をArchiveに変えていましたが、元々のリンク先が復活していたので、元に戻します。
※ revertするとコンフリクトしたため、このcommit https://github.com/azu/promises-book/commit/289422afb443483d061afe1847a99c923b419788 で対応しています。

chore: erights.orgのリンク切れが復活していたので対応

---

CONTRIBUTING.md

chore: fix broken link

---

package.json
yarn.lock

[npm-run-all](https://github.com/mysticatea/npm-run-all) はメンテナンスされなくなってしまっているので、  
[npm-run-all2](https://github.com/bcomnes/npm-run-all2) へ移行しました  
また、dependencies の中に入っていましたが、開発時のみに使用しているものかと思うので、devDependencies に変えています   
.node-version が v18.16.1 だったため、最新版ではなく、対応しているバージョンであるv6を入れています
<https://github.com/bcomnes/npm-run-all2/blob/master/CHANGELOG.md>

chore: npm-run-all から npm-run-all2 へ移行

---

package.json
yarn.lock

npm-run-all2 を v6 → v8 へアップデート
- <https://github.com/noritaka1166/npm-run-all2/blob/master/CHANGELOG.md>

chore: npm-run-all2 を v6 → v8 へアップデート

---

Ch4_AdvancedPromises/test/fs-method-chain-test.js
Ch4_AdvancedPromises/test/fs-promise-chain-test.js
package.json
yarn.lock

~~fs-extra を v8 → v11 へアップデート~~
- ~~<https://github.com/jprichardson/node-fs-extra/blob/master/CHANGELOG.md>~~
fs-extra を使わずに node:fs を使うようにした

refactor: fs-extra を使わずに node:fs を使うようにした

---

package.json
yarn.lock

gulp を v4 → v5 へアップデート
- <https://github.com/gulpjs/gulp/blob/master/CHANGELOG.md>

chore: gulp を v4 → v5 へアップデート

---

_tools/gulp/format-code.js
package.json

`format-code.js` で [through2](https://github.com/rvagg/through2) を使わず node の stream を使うようにした

refactor: through2 を使わず node の stream を使うようにした

---

.mocharc.json
package.json
test/echo-server.js
test/html/missing-internal-link.js
test/inline-script/inline-script-tester.js
test/mocha.opts
test/node-helper.js
yarn.lock

mocha を v6→v11 へアップデート
- <https://github.com/mochajs/mocha/blob/main/CHANGELOG.md>
- 合わせて、testディレクトリ配下のeslint の error/warning の対応を実施

refactor: mocha を v6→v11 へアップデート
